ARG NODE_ENV=production

FROM node:20-alpine AS base
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

FROM base AS deps
WORKDIR /app
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

COPY package.json package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm npm ci --include=dev --prefer-offline --no-audit

FROM base AS builder
WORKDIR /app
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

ARG NEXT_PUBLIC_SEARXNG_URL
ARG NEXT_PUBLIC_SEARXNG_SEARCH_PATH=/search
ARG SEARXNG_FALLBACK_ENABLED=true
ENV NEXT_PUBLIC_SEARXNG_URL=$NEXT_PUBLIC_SEARXNG_URL
ENV NEXT_PUBLIC_SEARXNG_SEARCH_PATH=$NEXT_PUBLIC_SEARXNG_SEARCH_PATH
ENV SEARXNG_FALLBACK_ENABLED=$SEARXNG_FALLBACK_ENABLED

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

FROM base AS runner
WORKDIR /app

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_SEARXNG_URL
ARG NEXT_PUBLIC_SEARXNG_SEARCH_PATH=/search
ARG SEARXNG_FALLBACK_ENABLED=true
ENV NEXT_PUBLIC_SEARXNG_URL=$NEXT_PUBLIC_SEARXNG_URL
ENV NEXT_PUBLIC_SEARXNG_SEARCH_PATH=$NEXT_PUBLIC_SEARXNG_SEARCH_PATH
ENV SEARXNG_FALLBACK_ENABLED=$SEARXNG_FALLBACK_ENABLED

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

ARG HOSTNAME=0.0.0.0
ENV HOSTNAME=$HOSTNAME

ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT

CMD ["node", "server.js"] 